
## Problem
---


Anda adalah seorang Data Analyst yang akan mengerjakan sebuah project untuk menyelesaikan permasalahan seorang client. Client Anda membutuhkan hasil analisa data yang menggunakan statistik dan dashboard visualisasi untuk membantu mereka menyelesaikan masalahnya.

---
## Objectives
---


*Pengerjaan* ini dibuat dengan tujuan sebagai berikut :

- Bagaimana tren penjualan bulanan ?.

- Bagaimana penjualan bedasarkan product category?.

- bagaimana penjualan berdasarkan age category?.

- bagaimana penjualan berdasarkan lokasi?.

- bagaimana statistik deskriptif berdasarkan penjualan

- bagaimana korelasi antara session duration minutes, page view dan quantity?.
---


## Data Processing
---


In [1]:
# Package
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

In [2]:
# Load Data
df = pd.read_csv('Pengerjaan.csv')
df.head()

Order_ID Customer_ID        Date  Age  Gender      City Product_Category  \
0  ORD_001337  CUST_01337  2023-01-01   27  Female     Bursa             Toys   
1  ORD_004885  CUST_04885  2023-01-01   42    Male     Konya             Toys   
2  ORD_004507  CUST_04507  2023-01-01   43  Female    Ankara             Food   
3  ORD_000645  CUST_00645  2023-01-01   32    Male  Istanbul      Electronics   
4  ORD_000690  CUST_00690  2023-01-01   40  Female  Istanbul           Sports   

   Unit_Price  Quantity  Discount_Amount  Total_Amount    Payment_Method  \
0       54.28         1             0.00         54.28        Debit Card   
1      244.90         1             0.00        244.90       Credit Card   
2       48.15         5             0.00        240.75       Credit Card   
3      804.06         1           229.28        574.78       Credit Card   
4      755.61         5             0.00       3778.05  Cash on Delivery   

  Device_Type  Session_Duration_Minutes  Pages_Viewed  Is_Returning_Customer  \
0      Mobile                         4            14                   True   
1      Mobile                        11             3                   True   
2      Mobile                         7             8                   True   
3      Mobile                         8            10                  False   
4     Desktop                        21            10                   True   

   Delivery_Time_Days  Customer_Rating  
0                   8                5  
1                   3                3  
2                   5                2  
3                   1                4  
4                   7                4

In [3]:
# Sumaary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Order_ID                  5000 non-null   object 
 1   Customer_ID               5000 non-null   object 
 2   Date                      5000 non-null   object 
 3   Age                       5000 non-null   int64  
 4   Gender                    5000 non-null   object 
 5   City                      5000 non-null   object 
 6   Product_Category          5000 non-null   object 
 7   Unit_Price                5000 non-null   float64
 8   Quantity                  5000 non-null   int64  
 9   Discount_Amount           5000 non-null   float64
 10  Total_Amount              5000 non-null   float64
 11  Payment_Method            5000 non-null   object 
 12  Device_Type               5000 non-null   object 
 13  Session_Duration_Minutes  5000 non-null   int64  
 14  Pages_Vi

Dataset memiliki:
- 5000 rows
- 18 kolom
- 670 kb memory

dari dataset masih memiliki inconsisten datatype pada date. selanjutnya akan dilakukan handling datatype

In [4]:
# handling Datatype
df['Date'] = pd.to_datetime(df['Date'],yearfirst=True)
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype         
---  ------                    --------------  -----         
 0   Order_ID                  5000 non-null   object        
 1   Customer_ID               5000 non-null   object        
 2   Date                      5000 non-null   datetime64[ns]
 3   Age                       5000 non-null   int64         
 4   Gender                    5000 non-null   object        
 5   City                      5000 non-null   object        
 6   Product_Category          5000 non-null   object        
 7   Unit_Price                5000 non-null   float64       
 8   Quantity                  5000 non-null   int64         
 9   Discount_Amount           5000 non-null   float64       
 10  Total_Amount              5000 non-null   float64       
 11  Payment_Method            5000 non-null   object        
 12  Device_Type         

dataset:
- datatype Date telah berubah 
- tidak memiliki missing value

dari dataset telah dilakukan perubahan pada datatype, sekarang akan dilakukan checking duplicated

In [5]:
# Checking Duplicated
df.duplicated().sum()

0

dataset tidak memiliki data duplicated. selanjurnya checking missing value

In [6]:
pd.set_option('display.max_colwidth', None)

cols = list(df.select_dtypes(include='object').columns)

listItem = []
for col in cols:
  listItem.append([col, df[col].nunique(), df[col].unique()])

pd.DataFrame(columns=['nama kolom', 'jumlah nilai unique', 'nilai unique'], data=listItem)

nama kolom  jumlah nilai unique  \
0          Order_ID                 5000   
1       Customer_ID                 5000   
2            Gender                    3   
3              City                   10   
4  Product_Category                    8   
5    Payment_Method                    5   
6       Device_Type                    3   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nilai unique  
0  [ORD_001337, ORD_004885, ORD_004507, ORD_000645, ORD_000690, ORD_000223, ORD_002506, ORD_004540, ORD_001808, ORD_003413, ORD_004457, ORD_004797, ORD_001211, ORD_000514, ORD_003462, ORD_001418, ORD_000198, ORD_000374, ORD_003204, ORD_004204, ORD_000751, ORD_002466, ORD_003920, ORD_000038, ORD_003721, ORD_002069, ORD_002080, ORD_000285, ORD_000846, ORD_003744, ORD_003991, ORD_003301, ORD_004873, ORD_002003, ORD_003730, ORD_001602, ORD_000477, ORD_002957, ORD_001565, ORD_000527, ORD_004551, ORD_004850, ORD_000450, ORD_003803, ORD_004585, ORD_003246, ORD_004291, ORD_004550, ORD_004883, ORD_000182, ORD_004113, ORD_004744, ORD_001054, ORD_003313, ORD_003948, ORD_000991, ORD_004801, ORD_001144, ORD_004740, ORD_004656, ORD_003748, ORD_003622, ORD_001373, ORD_004676, ORD_001127, ORD_003274, ORD_001822, ORD_000359, ORD_001477, ORD_001690, ORD_003755, ORD_003743, ORD_004501, ORD_002535, ORD_003836, ORD_003039, ORD_002497, ORD_003749, ORD_004673, ORD_001072, ORD_003669, ORD_001829, ORD_003491, ORD_003083, ORD_000227, ORD_002321, ORD_002468, ORD_002102, ORD_000912, ORD_001284, ORD_000839, ORD_002117, ORD_002525, ORD_000279, ORD_001784, ORD_000928, ORD_001597, ORD_003464, ORD_004168, ORD_002937, ...]  
1  [CUST_01337, CUST_04885, CUST_04507, CUST_00645, CUST_00690, CUST_00223, CUST_02506, CUST_04540, CUST_01808, CUST_03413, CUST_04457, CUST_04797, CUST_01211, CUST_00514, CUST_03462, CUST_01418, CUST_00198, CUST_00374, CUST_03204, CUST_04204, CUST_00751, CUST_02466, CUST_03920, CUST_00038, CUST_03721, CUST_02069, CUST_02080, CUST_00285, CUST_00846, CUST_03744, CUST_03991, CUST_03301, CUST_04873, CUST_02003, CUST_03730, CUST_01602, CUST_00477, CUST_02957, CUST_01565, CUST_00527, CUST_04551, CUST_04850, CUST_00450, CUST_03803, CUST_04585, CUST_03246, CUST_04291, CUST_04550, CUST_04883, CUST_00182, CUST_04113, CUST_04744, CUST_01054, CUST_03313, CUST_03948, CUST_00991, CUST_04801, CUST_01144, CUST_04740, CUST_04656, CUST_03748, CUST_03622, CUST_01373, CUST_04676, CUST_01127, CUST_03274, CUST_01822, CUST_00359, CUST_01477, CUST_01690, CUST_03755, CUST_03743, CUST_04501, CUST_02535, CUST_03836, CUST_03039, CUST_02497, CUST_03749, CUST_04673, CUST_01072, CUST_03669, CUST_01829, CUST_03491, CUST_03083, CUST_00227, CUST_02321, CUST_02468, CUST_02102, CUST_00912, CUST_01284, CUST_00839, CUST_02117, CUST_02525, CUST_00279, CUST_01784, CUST_00928, CUST_01597, CUST_03464, CUST_04168, CUST_02937, ...]  
2                      

In [7]:
cols = list(df.select_dtypes(include='number').columns)

listItem = []
for col in cols:
  listItem.append([col, df[col].nunique(), df[col].unique()])

pd.DataFrame(columns=['nama kolom', 'jumlah nilai unique', 'nilai unique'], data=listItem)

nama kolom  jumlah nilai unique  \
0                       Age                   57   
1                Unit_Price                 4785   
2                  Quantity                    5   
3           Discount_Amount                 1405   
4              Total_Amount                 4868   
5  Session_Duration_Minutes                   58   
6              Pages_Viewed                   22   
7        Delivery_Time_Days                   25   
8           Customer_Rating                    5   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  nilai unique  
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [27, 42, 43, 32, 40, 25, 44, 41, 58, 21, 20, 24, 57, 38, 36, 46, 50, 23, 45, 34, 18, 52, 29, 60, 37, 39, 51, 22, 53, 35, 33, 31, 26, 30, 47, 28, 49, 61, 19, 66, 55, 48, 59, 54, 56, 62, 63, 64, 65, 73, 71, 75, 72, 68, 67, 70, 69]  
1              [54.28, 244.9, 48.15, 804.06, 755.61, 122.46, 2107.37, 213.64, 257.62, 1784.75, 1091.11, 77.06, 197.88, 897.02, 37.19, 41.21, 81.91, 431.85, 696.98, 1837.61, 22.64, 930.97, 181.48, 78.21, 4136.98, 240.87, 443.53, 912.21, 1375.1, 453.05, 288.26, 724.61, 37.68, 1148.64, 544.6, 131.04, 181.88, 46.09, 280.4, 746.9, 129.16, 21.87, 77.6, 1624.97, 101.55, 530.65, 182.14, 153.87, 103.15, 164.61, 326.33, 44.85, 51.32, 533.72, 216.82, 117.12, 1016.3, 109.93, 1228.33, 674.39, 118.37, 145.58, 53.25, 74.51, 536.13, 484.14, 154.14, 94.59, 71.42, 246.03, 371.2, 402.95, 370.25, 165.99, 23.55, 105.69, 476.38, 476.23, 450.42, 32.92, 131.77, 105.36, 1652.27, 78.19, 103.02, 480.97, 428.98, 86.39, 54.43, 275.71, 53.31, 97.74, 1148.11, 160.45, 41.11, 185.71, 434.12, 1860.25, 673.1, 785.15, ...]  
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [1, 5, 2, 4, 3]  
3                                                                                             [0.0, 229.28, 62.15, 490.25, 15.22, 8.76, 100.24, 156.33, 1.65, 190.12, 1137.7, 36.98, 63.68, 61.33, 74.6, 26.42, 14.33, 10.69, 32.66, 28.42, 31.05, 100.41, 25.45, 2.71, 21.55, 2.11, 14.0, 68.97, 26

dari semua telah melakukan:
- Handling datatype
- Check duplicated
- Check missing value

dataset bersih tidak ada value aneh. telah bisa lanjut ketahap selanjutnya



## Exploration Data Analysis
---


### Trend Penjualan Bulanan

In [8]:
df["Periode_Bulan"] = df["Date"].dt.to_period("M").astype(str)
Trend_Bulanan = df.groupby("Periode_Bulan").agg({
    "Total_Amount": "sum",
    "Quantity":"count"
}).round().reset_index()
Trend_Bulanan


Periode_Bulan  Total_Amount  Quantity
0        2023-01      286694.0       301
1        2023-02      338785.0       334
2        2023-03      321716.0       344
3        2023-04      257333.0       281
4        2023-05      351902.0       355
5        2023-06      324357.0       349
6        2023-07      346618.0       342
7        2023-08      391506.0       371
8        2023-09      262603.0       306
9        2023-10      352287.0       361
10       2023-11      282606.0       336
11       2023-12      384718.0       367
12       2024-01      396875.0       358
13       2024-02      342913.0       307
14       2024-03      274633.0       288

In [9]:
x = Trend_Bulanan['Periode_Bulan']
y = Trend_Bulanan['Total_Amount']
plt.plot(x, y)
plt.title("Trend Bulanan Line Chart")
plt.xlabel("")
plt.ylabel("Y")
plt.show()

dari tren bulana:
- Ada tren musiman kuat: peningkatan di Agustus, Desember, dan awal tahun (Januari).
- Pergerakan total penjualan sangat mirip dengan quantity, artinya harga produk relatif stabil.
- Kinerja 2024 awal lebih kuat daripada tahun 2023.

### Penjualan berdasarkan Product Category

In [10]:
product = df.groupby("Product_Category").agg({
    "Total_Amount": "sum",
    "Quantity":"count",
    "Unit_Price":'median'
}).round().reset_index()
product

Product_Category  Total_Amount  Quantity  Unit_Price
0           Beauty      156585.0       621        94.0
1            Books       72745.0       616        50.0
2      Electronics     2328807.0       624      1472.0
3          Fashion      375215.0       622       235.0
4             Food       96139.0       619        61.0
5    Home & Garden      908349.0       621       590.0
6           Sports      754564.0       667       418.0
7             Toys      223142.0       610       141.0

In [11]:
plt.bar(product['Product_Category'],product['Total_Amount'])
plt.show()



dari category product:
- lectronics adalah kategori paling profitable, sebagian besar karena harga satuannya jauh lebih tinggi.
- Sports punya kuantitas terjual tertinggi, tapi tidak mengalahkan revenue Electronics.
- Books dan Food memiliki harga dan revenue paling rendah, meskipun jumlah unitnya tidak jauh dari kategori lain.
- Penjualan kuantitas antar kategori relatif stabil, menunjukkan tidak ada kategori yang "tidak laku", tetapi nilai transaksinya sangat berbeda karena harga.

### Penjualan Berdasarkan Category Age

In [12]:
df['Category_Age'] = (
    df['Age']
        .apply(lambda x: 'Remaja' if x <= 20 else 'Dewasa' if x <= 40 else 'Tua')
)
Category_Costumer = df.groupby("Category_Age").agg({
    "Total_Amount": "sum",
    "Quantity":"count"
}).round().reset_index()
Category_Costumer

Category_Age  Total_Amount  Quantity
0       Dewasa     2726802.0      2856
1       Remaja      619412.0       595
2          Tua     1569331.0      1549

In [13]:
plt.pie(Category_Costumer['Total_Amount'], labels=Category_Costumer['Category_Age'], autopct='%1.1f%%')
plt.show()


dari profit berdasarkan Category Age:
-  category dewasa memiliki profit dan jumlah order terbesar dengan 2726802.0 TRY dan 2856 order
-  disusul category tua dengan 1569331.0 TRY dan 1549
-  remaja profit dan jumlah order terkecil dengan 619412.0 TRY dan 595

### Penjualan Berdasarkan Lokasi

In [14]:
lokasi = df.groupby("City").agg({
    "Total_Amount": "sum",
    "Quantity":"count"
}).round().reset_index()
lokasi

City  Total_Amount  Quantity
0      Adana      427060.0       378
1     Ankara      657536.0       735
2    Antalya      315550.0       374
3      Bursa      459076.0       496
4  Eskisehir      178978.0       210
5  Gaziantep      318408.0       349
6   Istanbul     1334123.0      1284
7      Izmir      567535.0       600
8    Kayseri      312304.0       257
9      Konya      344975.0       317

In [15]:
plt.barh(lokasi['City'],lokasi['Total_Amount'])
plt.show()

dari profi berdasarkan lokasi:
-  istanbul memiliki profit dan jumlah order terbesar dengan 1334123.0 TRY dan 1284 order
-  Eskisehir profit dan jumlah order terkecil dengan 178978.0 TRY dan 210

### Statistik Deskriptif Penjualan

In [16]:
i = df['Total_Amount'].describe().round()
pd.DataFrame(i)

Total_Amount
count        5000.0
mean          983.0
std          1899.0
min             8.0
25%           123.0
50%           338.0
75%           980.0
max         22024.0

dari Deskriptif :
- memiliki 5000 order
- dengan penjualan terendah 8 TRY, penjulan tertinggi 22024 TRY
- nilai tengah penjualan 338 TRY
- dan rata2 983 TRY

kesimpulan dari deskriptif:
- Banyak transaksi bernilai kecil/menengah, namun sedikit transaksi bernilai sangat besar yang menarik rata-rata menjadi tinggi.

### Kolerasi Session_Duration_Minutes vs Quantity dan Pages_Viewed vs Quantity

In [17]:
corr_r_duration_view, pval_p_duration_view = stats.pearsonr(df['Session_Duration_Minutes'], df['Quantity'])
corr_r_page_view, pval_p_page_view = stats.pearsonr(df['Pages_Viewed'], df['Quantity'])

print(f"r-correlation: {corr_r_duration_view:.3f}, p-value: {pval_p_duration_view:.3f}")
print(f"r-correlation: {corr_r_page_view:.3f}, p-value: {pval_p_page_view:.3f}")

pd.DataFrame({
    'Index':['r-correlation','p-value'],
    'Duration_View':[corr_r_page_view,corr_r_duration_view],
    'Page_View':[pval_p_page_view,pval_p_duration_view] 
})

r-correlation: -0.006, p-value: 0.652
r-correlation: -0.004, p-value: 0.755


Index  Duration_View  Page_View
0  r-correlation      -0.004417   0.754822
1        p-value      -0.006383   0.651835

Gambar tersebut menunjukkan Anda sedang melakukan uji korelasi Pearson (stats.pearsonr) antara dua variabel numerik:
- Session_Duration_Minutes vs Quantity
- Pages_Viewed vs Quantity

Kesimpulan:
- Durasi session tidak memiliki hubungan dengan jumlah pembelian. Tidak ada bukti statistik bahwa semakin lama session, semakin banyak (atau sedikit) Quantity.
- Jumlah halaman yang dilihat tidak berpengaruh terhadap Quantity. Tidak ada hubungan antara keduanya